#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <SDL2/SDL.h>

/* remapping some of the default SDL2 enums to something more user friendly */
enum Button{
	BUTTON_LEFT_CLICK=SDL_BUTTON_LEFT,
	BUTTON_RIGHT_CLICK=SDL_BUTTON_RIGHT,
	BUTTON_MIDDLE_CLICK=SDL_BUTTON_MIDDLE
};

enum Key {
	/* arrow keys */
	KEY_UP=SDL_SCANCODE_UP,
	KEY_DOWN=SDL_SCANCODE_DOWN,
	KEY_LEFT=SDL_SCANCODE_LEFT,
	KEY_RIGHT=SDL_SCANCODE_RIGHT,
	/* letters */
	KEY_A=SDL_SCANCODE_A,
	KEY_B=SDL_SCANCODE_B,
	KEY_C=SDL_SCANCODE_C,
	KEY_D=SDL_SCANCODE_D,
	KEY_E=SDL_SCANCODE_E,
	KEY_F=SDL_SCANCODE_F,
	KEY_G=SDL_SCANCODE_G,
	KEY_H=SDL_SCANCODE_H,
	KEY_I=SDL_SCANCODE_I,
	KEY_J=SDL_SCANCODE_J,
	KEY_K=SDL_SCANCODE_K,
	KEY_L=SDL_SCANCODE_L,
	KEY_M=SDL_SCANCODE_M,
	KEY_N=SDL_SCANCODE_N,
	KEY_O=SDL_SCANCODE_O,
	KEY_P=SDL_SCANCODE_P,
	KEY_Q=SDL_SCANCODE_Q,
	KEY_R=SDL_SCANCODE_R,
	KEY_S=SDL_SCANCODE_S,
	KEY_T=SDL_SCANCODE_T,
	KEY_U=SDL_SCANCODE_U,
	KEY_V=SDL_SCANCODE_V,
	KEY_W=SDL_SCANCODE_W,
	KEY_X=SDL_SCANCODE_X,
	KEY_Y=SDL_SCANCODE_Y,
	KEY_Z=SDL_SCANCODE_Z,
	/* numbers */
	KEY_ZERO=SDL_SCANCODE_0,
	KEY_ONE=SDL_SCANCODE_1,
	KEY_TWO=SDL_SCANCODE_2,
	KEY_THREE=SDL_SCANCODE_3,
	KEY_FOUR=SDL_SCANCODE_4,
	KEY_FIVE=SDL_SCANCODE_5,
	KEY_SIX=SDL_SCANCODE_6,
	KEY_SEVEN=SDL_SCANCODE_7,
	KEY_EIGHT=SDL_SCANCODE_8,
	KEY_NINE=SDL_SCANCODE_9,
	/* special characters */
	KEY_SHIFT_LEFT=SDL_SCANCODE_LSHIFT,
	KEY_SHIFT_RIGHT=SDL_SCANCODE_RSHIFT,
	KEY_TAB=SDL_SCANCODE_TAB,
	KEY_CAPS_LOCK=SDL_SCANCODE_CAPSLOCK,
	KEY_TILDE=SDL_SCANCODE_GRAVE,
	KEY_LEFT_CONTROL=SDL_SCANCODE_LCTRL,
	KEY_RIGHT_CONTROL=SDL_SCANCODE_RCTRL,
	KEY_LEFT_ALT=SDL_SCANCODE_LALT,
	KEY_RIGHT_ALT=SDL_SCANCODE_RALT,
	KEY_ENTER=SDL_SCANCODE_RETURN,
	KEY_BACKSPACE=SDL_SCANCODE_BACKSPACE,
	KEY_ESCAPE=SDL_SCANCODE_ESCAPE
};
#endif